name: YepSVGSampleApp
options:
  minimumXcodeGenVersion: 2.44.1
  deploymentTarget:
    iOS: "15.0"
settings:
  base:
    SWIFT_VERSION: 6.0
    PRODUCT_BUNDLE_IDENTIFIER: com.yepngo.YepSVGSampleApp
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""
    GENERATE_INFOPLIST_FILE: YES
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
packages:
  YepSVG:
    path: ../..
targets:
  YepSVGSampleApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: YepSVGSampleApp/App
      - path: YepSVGSampleApp/Resources/badge.svg
        buildPhase: resources
      - path: YepSVGSampleApp/Resources/W3CSuite
        buildPhase: resources
        type: folder
    dependencies:
      - package: YepSVG
        product: YepSVG
schemes:
  YepSVGSampleApp:
    build:
      targets:
        YepSVGSampleApp: all
    run:
      config: Debug
